const List<Map<String, String>> timezoneData = [
  {'name': 'UTC', 'label': 'UTC (Coordinated Universal Time)'},
  {'name': 'America/New_York', 'label': 'America/New_York (Eastern Time)'},
  {'name': 'America/Chicago', 'label': 'America/Chicago (Central Time)'},
  {'name': 'America/Denver', 'label': 'America/Denver (Mountain Time)'},
  {'name': 'America/Los_Angeles', 'label': 'America/Los_Angeles (Pacific Time)'},
  {'name': 'America/Anchorage', 'label': 'America/Anchorage (Alaska Time)'},
  {'name': 'Pacific/Honolulu', 'label': 'Pacific/Honolulu (Hawaii Time)'},
  {'name': 'America/Phoenix', 'label': 'America/Phoenix (Arizona Time)'},
  {'name': 'Europe/London', 'label': 'Europe/London (Greenwich Mean Time)'},
  {'name': 'Europe/Paris', 'label': 'Europe/Paris (Central European Time)'},
  {'name': 'Europe/Berlin', 'label': 'Europe/Berlin (Central European Time)'},
  {'name': 'Europe/Madrid', 'label': 'Europe/Madrid (Central European Time)'},
  {'name': 'Europe/Rome', 'label': 'Europe/Rome (Central European Time)'},
  {'name': 'Europe/Amsterdam', 'label': 'Europe/Amsterdam (Central European Time)'},
  {'name': 'Europe/Brussels', 'label': 'Europe/Brussels (Central European Time)'},
  {'name': 'Europe/Vienna', 'label': 'Europe/Vienna (Central European Time)'},
  {'name': 'Europe/Stockholm', 'label': 'Europe/Stockholm (Central European Time)'},
  {'name': 'Europe/Oslo', 'label': 'Europe/Oslo (Central European Time)'},
  {'name': 'Europe/Copenhagen', 'label': 'Europe/Copenhagen (Central European Time)'},
  {'name': 'Europe/Helsinki', 'label': 'Europe/Helsinki (Eastern European Time)'},
  {'name': 'Europe/Bucharest', 'label': 'Europe/Bucharest (Eastern European Time)'},
  {'name': 'Europe/Sofia', 'label': 'Europe/Sofia (Eastern European Time)'},
  {'name': 'Europe/Athens', 'label': 'Europe/Athens (Eastern European Time)'},
  {'name': 'Europe/Moscow', 'label': 'Europe/Moscow (Moscow Time)'},
  {'name': 'Asia/Dubai', 'label': 'Asia/Dubai (Gulf Standard Time)'},
  {'name': 'Asia/Bangkok', 'label': 'Asia/Bangkok (Indochina Time)'},
  {'name': 'Asia/Singapore', 'label': 'Asia/Singapore (Singapore Time)'},
  {'name': 'Asia/Kuala_Lumpur', 'label': 'Asia/Kuala_Lumpur (Malaysia Time)'},
  {'name': 'Asia/Jakarta', 'label': 'Asia/Jakarta (Western Indonesia Time)'},
  {'name': 'Asia/Hong_Kong', 'label': 'Asia/Hong_Kong (Hong Kong Time)'},
  {'name': 'Asia/Shanghai', 'label': 'Asia/Shanghai (China Standard Time)'},
  {'name': 'Asia/Beijing', 'label': 'Asia/Beijing (China Standard Time)'},
  {'name': 'Asia/Tokyo', 'label': 'Asia/Tokyo (Japan Standard Time)'},
  {'name': 'Asia/Seoul', 'label': 'Asia/Seoul (Korea Standard Time)'},
  {'name': 'Asia/Manila', 'label': 'Asia/Manila (Philippine Time)'},
  {'name': 'Asia/Kolkata', 'label': 'Asia/Kolkata (India Standard Time)'},
  {'name': 'Asia/Colombo', 'label': 'Asia/Colombo (Sri Lanka Time)'},
  {'name': 'Asia/Dhaka', 'label': 'Asia/Dhaka (Bangladesh Time)'},
  {'name': 'Asia/Karachi', 'label': 'Asia/Karachi (Pakistan Standard Time)'},
  {'name': 'Asia/Tehran', 'label': 'Asia/Tehran (Iran Standard Time)'},
  {'name': 'Asia/Baghdad', 'label': 'Asia/Baghdad (Arabia Standard Time)'},
  {'name': 'Asia/Riyadh', 'label': 'Asia/Riyadh (Arabian Standard Time)'},
  {'name': 'Asia/Jerusalem', 'label': 'Asia/Jerusalem (Israel Standard Time)'},
  {'name': 'Africa/Cairo', 'label': 'Africa/Cairo (Egypt Standard Time)'},
  {'name': 'Africa/Johannesburg', 'label': 'Africa/Johannesburg (South Africa Standard Time)'},
  {'name': 'Africa/Lagos', 'label': 'Africa/Lagos (West Africa Time)'},
  {'name': 'Africa/Nairobi', 'label': 'Africa/Nairobi (East Africa Time)'},
  {'name': 'Australia/Sydney', 'label': 'Australia/Sydney (Australian Eastern Time)'},
  {'name': 'Australia/Melbourne', 'label': 'Australia/Melbourne (Australian Eastern Time)'},
  {'name': 'Australia/Brisbane', 'label': 'Australia/Brisbane (Australian Eastern Time)'},
  {'name': 'Australia/Adelaide', 'label': 'Australia/Adelaide (Australian Central Time)'},
  {'name': 'Australia/Perth', 'label': 'Australia/Perth (Australian Western Time)'},
  {'name': 'Pacific/Auckland', 'label': 'Pacific/Auckland (New Zealand Time)'},
  {'name': 'Pacific/Fiji', 'label': 'Pacific/Fiji (Fiji Time)'},
  {'name': 'Pacific/Tahiti', 'label': 'Pacific/Tahiti (Tahiti Time)'},
  {'name': 'Pacific/Honolulu', 'label': 'Pacific/Honolulu (Hawaii-Aleutian Time)'},
  {'name': 'America/Toronto', 'label': 'America/Toronto (Eastern Time - Canada)'},
  {'name': 'America/Vancouver', 'label': 'America/Vancouver (Pacific Time - Canada)'},
  {'name': 'America/Mexico_City', 'label': 'America/Mexico_City (Central Time - Mexico)'},
  {'name': 'America/Sao_Paulo', 'label': 'America/Sao_Paulo (Brasilia Time)'},
  {'name': 'America/Buenos_Aires', 'label': 'America/Buenos_Aires (Argentina Time)'},
  {'name': 'America/Santiago', 'label': 'America/Santiago (Chile Time)'},
  {'name': 'America/Lima', 'label': 'America/Lima (Peru Time)'},
  {'name': 'America/Bogota', 'label': 'America/Bogota (Colombia Time)'},
  {'name': 'Europe/Lisbon', 'label': 'Europe/Lisbon (Western European Time)'},
  {'name': 'Europe/Dublin', 'label': 'Europe/Dublin (Irish Standard Time)'},
  {'name': 'Europe/Warsaw', 'label': 'Europe/Warsaw (Central European Time)'},
  {'name': 'Europe/Prague', 'label': 'Europe/Prague (Central European Time)'},
  {'name': 'Europe/Budapest', 'label': 'Europe/Budapest (Central European Time)'},
  {'name': 'Europe/Belgrade', 'label': 'Europe/Belgrade (Central European Time)'},
];
